#Stage 1: Simple Monoalphabetic Substitution Cipher

code = 	"CVM, TXRRX LCLXTJC, XBR KUX RUVWBVML NXNCR NX LMC PULMTM M \
		XRAVXDXV, NXIVCTJX NC AMTNXGMFVC, TC VXDXRJBLXTJC NM QMVXNX \
		NC QMGMABC VXMG. C VXB, M DBRJM NXRRM LMC KUX XRAVXDBM, LUNCU \
		NX ACV; QXTRMLXTJCR JXJVBACR MRRMGJMVML-TC; CR LURAUGCR NX \
		RXUR VBTR VXGMZMVML-RX X RXUR SCXGPCR XTJVXAPCAMVML-RX. \
		WVBJCU DBCGXTJMLXTJX KUX LMTNMRRXL DBV CR LMWC, CR AMGNXUR \
		X CR MRJVCGCWCR. LMTNCU-GPXR NBOXV: MKUXGX KUX NXABIVMV XRJM \
		BTRAVBAMC X LXNXV C RXTJBNC NXGM, RXVM VXDXRJBNC NX QUVQUVM, \
		TC WCDXVTC NC VXBTC. JCNCR CR RMFBCR NC VXB XTJVMVML TM RMGM, \
		LMR ICVML BTAMQMOXR NX GXV XRRM BTRAVBAMC X NMV-GPX C \
		RBWTBIBAMNC MC VXB. FMGJMOMV IBACU LUBJC MRRURJMNC, RXU \
		VCRJC LUNCU NX ACV, X RXUR TCFVXR RXTJBML-RX ACTRJVMTWBNCR. \
		LMR M VMBTPM, MJVMBNM QXGC FMVUGCP NMR QMGMDVMR NC VXBX NCR \
		TCFVXR, XTJVCU TM RMGM NC IXRJBL: C VXB, NBRRX, DBDX QMVM \
		RXLQVX! TMC JX NXBZXR MJXLCVBOMB QCV JUMR BNXBMR; TMC LUNXR \
		MRRBL NX ACV. PM TC JXU VXBTC UL PCLXLTC KUMG PMFBJM C \
		XRQBVBJC NCR NXURXR RMTJCR. KUMTNC JXU QMB XVM DBDC, \
		XTACTJVMDM-RX TXGX ULM GUO, ULM BTJXGBWXTABM X ULM RMFXNCVBM \
		ACLQMVMDXBR M RMFXNCVBM NCR NXURXR. QCV BRRC C VXB \
		TMFUACNCTCRCV, JXU QMB, JBTPM-C TCLMNC APXIX NCR XRAVBFMR, \
		NCR LMWCR, NCR AMGNXUR X NCR MRJVCFCWCR; PMDBM-RX NXRACFXVJC \
		TXRJX NMTBXG (ACWTCLBTMNC FMGJMOMV QXGC VXB) UL XRQBVBJC \
		RUQXVBCV, ULM ABXTABM X ULM QXTXJVMAMC QMVJBAUGMV QMVM \
		BTJXVQVXJMV CR RCTPCR, XZQGBAMV CR XTBWLMR X VXRCGDXV MR \
		RBWTBIBAMNC NM BTRAVBAMC. M QVBLXBVM QMGMDVM-ACNBWC X \
		CJPXGGC."